name: provider_learn
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.82.6
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  provider: ^6.1.1
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^9.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true
